name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Grant execute permission for gradlew
      run: chmod +x server/gradlew

    - name: Build with Gradle
      working-directory: server
      run: ./gradlew clean bootJar

    - name: Find built jar
      id: find_jar
      run: |
        JAR_FILE=$(ls server/build/libs/*.jar | head -n 1 | xargs -n 1 basename)
        echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_ENV

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          echo "=== 8080 포트에서 실행 중인 프로세스 종료 중 ==="
          PID=$(lsof -ti:8080)
          if [ -n "$PID" ]; then
            sudo kill -9 $PID
            echo "8080 포트 프로세스 종료 완료"
          else
            echo "8080 포트에서 실행 중인 프로세스가 없습니다."
          fi
          echo "=== 기존 JAR 파일 삭제 ==="
          rm -f /home/ubuntu/*.jar

    - name: Copy jar to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: server/build/libs/${{ env.JAR_FILE }}
        target: /home/ubuntu/

    - name: Start Application
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          echo "=== 애플리케이션 실행 중 ==="
          sudo nohup java -jar ${{ env.JAR_FILE }} &
